package main

func main() {
	panic("Not supposed to be called!")
}
